
package com.ztzf.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "Function", targetNamespace = "http://webService.ztzf.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface Function {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "transWords", targetNamespace = "http://webService.ztzf.com/", className = "com.ztzf.client.TransWords")
    @ResponseWrapper(localName = "transWordsResponse", targetNamespace = "http://webService.ztzf.com/", className = "com.ztzf.client.TransWordsResponse")
    @Action(input = "http://webService.ztzf.com/Function/transWordsRequest", output = "http://webService.ztzf.com/Function/transWordsResponse")
    public String transWords(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
